title: Servicios
preset: page
pages: false
fields:
  banner:
    label: Banner
    type: files
    max: 1
    template: image
    layout: cards
    width: 1/2
  resBanner:
    label: Banner para móvil
    type: files
    max: 1
    template: image
    layout: cards
    width: 1/2
    help: Opcional
  header:
    label: Encabezado
    type: textarea
    size: small
  positionX:
    label: Alineación horizontal del encabezado
    type: select
    default: left
    width: 1/2
    required: true
    options:
      left: Izquierda
      center: Centrado
      right: Derecha
  positionY:
    label: Alineación vertical del encabezado
    type: select
    default: center
    width: 1/2
    required: true
    options:
      top: Arriba
      center: Centrado
      bottom: Abajo
  textAlign:
    label: Alineación del texto encabezado
    type: select
    default: start
    width: 1/2
    required: true
    options:
      start: Izquierda
      center: Centrado
      end: Derecha
  textColor:
    label: Color del encabezado
    type: select
    default: white
    width: 1/2
    options:
      white: Blanco
      primary: Azul
      secondary: Verde
      text: Gris
  
  services:
    label: Servicios
    type: structure
    fields:
      media:
        label: Multimedia
        type: files
        template: media
        width: 1/3
        help: Carrusel de imágenes o un video
      text:
        label: Contenido
        type: textarea
        size: small
        width: 2/3
      useButton:
        label: Mostrar botón
        type: toggle
        width: 1/3
        text:
          - No mostrar
          - Mostrar
      buttonText:
        label: Etiqueta del botón
        type: text
        width: 2/3
      buttonPage:
        label: Página del botón
        type: pages
        max: 1
        width: 1/2
      buttonUrl:
        label: Url del botón
        type: url
        width: 1/2
        help: En caso de no seleccionar una página del sitio
      order:
        label: Posición del texto
        type: radio
        default: right
        options:
          right: Derecha
          left: Izquierda

  l1:
    type: line
      
  membershipsHeader:
    label: Encabezado de las membresías
    type: text
    width: 1/2

  h1:
    label: Plan gratuito
    type: headline
    numbered: false
  freeName:
    label: Nombre
    type: text
    width: 1/4
  freeDescription:
    label: Descripción
    type: text
    width: 3/4
  freeButtonText:
    label: Texto del botón
    type: text
    width: 1/4
  freeFeatures:
    label: Características
    type: list
    width: 3/4
  
  h2:
    label: Plan de paga
    type: headline
    numbered: false
  paidName:
    label: Nombre
    type: text
    width: 1/4
  paidPrice:
    label: Costo anual
    type: number
    width: 1/4
  paidDescription:
    label: Descripción
    type: text
    width: 2/4
  paidButtonText:
    label: Texto del botón
    type: text
    width: 1/4
  paidFeatures:
    label: Características
    type: list
    width: 3/4